export const services = [
  { id:'renovation', title:'Renovation & infrastructure', full:'Renovation & infrastructure upgrades', image:'image-5', label:'Civil works', intro:'Build new possibilities into existing spaces. Practical renovation and infrastructure solutions for commercial and industrial environments.', body:'From improving an existing facility to preparing infrastructure for its next stage, we bring civil works and renovation into one coordinated scope. Our focus is on understanding the site, protecting ongoing operations, and delivering work that supports the way your facility needs to function.', scope:['Commercial and industrial facility renovation','Civil works and infrastructure improvements','Site preparation and foundation-related works','Restoration and improvements to existing spaces'], approach:'We start with your existing conditions, access requirements, and intended use. Together, we define the work areas, sequencing, materials, and handover expectations before execution.', sectors:'Commercial buildings · Industrial facilities · Operational sites', brief:'Tell us about the existing facility, the improvements you need, and any restrictions on access or working hours.' },
  { id:'rtr-pipelines', title:'RTR pipeline solutions', full:'RTR pipeline solutions', image:'rtr-pipeline', label:'Pipeline systems', intro:'Corrosion-resistant pipeline solutions, installed with care and built around the needs of your operation.', body:'Reinforced Thermosetting Resin (RTR) pipelines offer corrosion resistance for a range of fluid transportation applications. Dynamic Contracting Company provides installation, maintenance, and repair services for these systems, with the scope developed around the application and project specifications.', scope:['RTR pipeline installation','Maintenance of existing RTR systems','Pipeline repair and replacement works','Coordination with connected infrastructure'], approach:'We review the service conditions, routing, connection details, and installation requirements with your team. Work is coordinated around the project specifications and the requirements of the selected pipeline system.', sectors:'Water infrastructure · Oil & gas · Petrochemical facilities', brief:'Share the pipeline application, approximate route and size, available specifications, and whether the work is a new installation or an existing-system repair.' },
  { id:'steel-pipelines', title:'CS & SS pipeline services', full:'Carbon & stainless steel pipelines', image:'steel', label:'Industrial piping', intro:'Fabrication, installation, and maintenance for the demands of industrial pipeline systems.', body:'Our carbon steel (CS) and stainless steel (SS) pipeline services support industrial operations where strength, reliability, and suitability for the intended service matter. We coordinate fabrication, installation, and maintenance around your drawings, material requirements, and site conditions.', scope:['Carbon steel pipeline fabrication and installation','Stainless steel pipeline fabrication and installation','Industrial piping maintenance','Repair and replacement of pipeline sections'], approach:'The starting point is a clear understanding of your pipeline duty, materials, drawings, and site interfaces. We align the execution scope and inspection requirements with your project team before work begins.', sectors:'Industrial facilities · Oil & gas · Process infrastructure', brief:'Include the material specification, pipe sizes, drawings if available, and any shutdown or tie-in requirements.' },
  { id:'electrical', title:'Electrical engineering', full:'Electrical engineering & installations', image:'electrical', label:'Power & systems', intro:'Connect your facility with electrical solutions that put safety, functionality, and efficient operation first.', body:'We support commercial and industrial facilities with electrical engineering and installation services, from wiring and system installations to power distribution and industrial automation. Our work is planned around the facility’s operating requirements and the interfaces with other project disciplines.', scope:['Power distribution installations','Commercial and industrial wiring','Electrical system installation and upgrades','Industrial automation support'], approach:'We review your electrical scope, available drawings, operational requirements, and installation environment. Coordination with the wider project team helps align access, work sequencing, and system interfaces.', sectors:'Commercial facilities · Industrial operations · Infrastructure', brief:'Tell us about the facility, the systems involved, the required upgrade or installation, and any available electrical drawings.' },
  { id:'fencing', title:'Fencing & security', full:'Fencing & security solutions', image:'fencing', label:'Perimeter protection', intro:'Define, protect, and secure your property with fencing tailored to its environment and purpose.', body:'We provide fencing solutions for commercial, industrial, and residential properties. From perimeter fencing to industrial barriers and security enclosures, we help define a practical scope that responds to the site layout, access needs, and required level of protection.', scope:['Property perimeter fencing','Industrial barriers','Security enclosures','Fencing installation and improvements'], approach:'We assess the boundary, ground conditions, access points, and intended use. The proposed fencing scope is coordinated with your site requirements, material preferences, and surrounding infrastructure.', sectors:'Industrial sites · Commercial properties · Residential properties', brief:'Share the approximate perimeter length, site location, preferred fence type, and any access or security requirements.' },
  { id:'environmental', title:'Environmental management', full:'Environmental management & compliance', image:'environmental', label:'Responsible delivery', intro:'Support responsible operations with practical environmental management and compliance-focused services.', body:'Our environmental services support businesses seeking to manage the environmental impact of their projects and operations. We focus on waste management, pollution control, and sustainability initiatives, with the service scope aligned to your project’s environmental requirements.', scope:['Project waste management support','Pollution control measures','Environmental compliance support','Sustainability and green initiatives'], approach:'We begin by understanding the activities involved, the environmental concerns, and the requirements identified for your project. We then agree the support needed and how it integrates with day-to-day site operations.', sectors:'Construction projects · Industrial facilities · Commercial operations', brief:'Describe the project activities, environmental concerns, existing requirements, and the support your team needs.' }
];
export const works = [
  { image:'image-7', title:'Lifting operations after dark', category:'structural', tag:'Structural works', text:'A view of lifting activity and structural materials during night-time site operations.' },
  { image:'image-5', title:'Infrastructure taking shape', category:'structural', tag:'Structural works', text:'Installed vertical steel members along a prepared construction work area.' },
  { image:'image-3', title:'The foundations of every build', category:'civil', tag:'Civil works', text:'Concrete foundations and anchor assemblies prepared for the next stage of construction.' },
  { image:'image-4', title:'Preparation at ground level', category:'civil', tag:'Civil works', text:'The site team carrying out excavation and ground preparation within a designated work area.' },
  { image:'image-1', title:'People at the heart of delivery', category:'people', tag:'Our people', text:'The project team assembled on site for a group briefing.' },
  { image:'image-6', title:'Ready for the next stage', category:'structural', tag:'Structural works', text:'Structural components arranged on site during evening construction activity.' },
  { image:'image-2', title:'Aligned before work begins', category:'people', tag:'Our people', text:'A closer look at a site team briefing with the workforce gathered in protective equipment.' }
];
